import { expect, test } from 'vitest';
import { StreamExtractor } from '../lib/stream-extractor';
import { ParserConfig } from '../lib/parser-config';
import { load } from './utils';


test('parse encrypt info from mpd without init', async () => {
  const { text, url } = await load('non-init-drm.mpd');

  const parseConfig = new ParserConfig();
  const streamExtractor = new StreamExtractor(parseConfig);
  streamExtractor.loadSourceFromText(text, url);
  const streams = await streamExtractor.extractStreams();

  const firstVideoTrack = streams.find((stream) => stream.type === 'video');
  const firstVideoSegment = firstVideoTrack?.playlist?.mediaParts[0]?.mediaSegments[0];
  expect(firstVideoSegment?.encryptInfo?.method).toBe('cenc');
  expect(firstVideoSegment?.encryptInfo?.drm?.widevine?.pssh).toBe('AAAAb3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAE8IARIgYjlmYTBhN2M2OWI2MzkxNjk4YmZjZWVjY2EyY2RjMjYaA2NkbiIkYzkyNTMyMjktNWE2NC1iMmU1LThjZDMtMDE1MDZlMmM5NGNh');
  expect(firstVideoSegment?.encryptInfo?.drm?.playready?.pssh).toBe('AAAD1HBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAA7S0AwAAAQABAKoDPABXAFIATQBIAEUAQQBEAEUAUgAgAHgAbQBsAG4AcwA9ACIAaAB0AHQAcAA6AC8ALwBzAGMAaABlAG0AYQBzAC4AbQBpAGMAcgBvAHMAbwBmAHQALgBjAG8AbQAvAEQAUgBNAC8AMgAwADAANwAvADAAMwAvAFAAbABhAHkAUgBlAGEAZAB5AEgAZQBhAGQAZQByACIAIAB2AGUAcgBzAGkAbwBuAD0AIgA0AC4AMAAuADAALgAwACIAPgA8AEQAQQBUAEEAPgA8AFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBFAFkATABFAE4APgAxADYAPAAvAEsARQBZAEwARQBOAD4APABBAEwARwBJAEQAPgBBAEUAUwBDAFQAUgA8AC8AQQBMAEcASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwASwBJAEQAPgBmAEEAcgA2AHUAYgBaAHAARgBqAG0AWQB2ADgANwBzAHkAaQB6AGMASgBnAD0APQA8AC8ASwBJAEQAPgA8AEMASABFAEMASwBTAFUATQA+AFUAMQBLAE4AUQA3AGgANQA2AG0AUQA9ADwALwBDAEgARQBDAEsAUwBVAE0APgA8AEwAQQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAGQAcgBtADkANQAzADcAMAAuAG4AbwB3AGQAcgBtAC4AYwBvAC8AcABsAGEAeQByAGUAYQBkAHkAPAAvAEwAQQBfAFUAUgBMAD4APABMAFUASQBfAFUAUgBMAD4AaAB0AHQAcABzADoALwAvAGQAcgBtADkANQAzADcAMAAuAG4AbwB3AGQAcgBtAC4AYwBvAC8AcABsAGEAeQByAGUAYQBkAHkAPAAvAEwAVQBJAF8AVQBSAEwAPgA8AEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAIAB4AG0AbABuAHMAPQAiACIAPgA8AEMAbwBuAHQAZQBuAHQAUgBlAGYAPgBjADkAMgA1ADMAMgAyADkALQA1AGEANgA0AC0AYgAyAGUANQAtADgAYwBkADMALQAwADEANQAwADYAZQAyAGMAOQA0AGMAYQA8AC8AQwBvAG4AdABlAG4AdABSAGUAZgA+ADwALwBDAFUAUwBUAE8ATQBBAFQAVABSAEkAQgBVAFQARQBTAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=');
});
