export const HLS_TAGS = {
  extM3u: '#EXTM3U',
  extXTargetDuration: '#EXT-X-TARGETDURATION',
  extXMediaSequence: '#EXT-X-MEDIA-SEQUENCE',
  extXDiscontinuitySequence: '#EXT-X-DISCONTINUITY-SEQUENCE',
  extXProgramDateTime: '#EXT-X-PROGRAM-DATE-TIME',
  extXMedia: '#EXT-X-MEDIA',
  extXPlaylistType: '#EXT-X-PLAYLIST-TYPE',
  extXKey: '#EXT-X-KEY',
  extXStreamInf: '#EXT-X-STREAM-INF',
  extXVersion: '#EXT-X-VERSION',
  extXAllowCache: '#EXT-X-ALLOW-CACHE',
  extXEndlist: '#EXT-X-ENDLIST',
  extInf: '#EXTINF',
  extIframesOnly: '#EXT-X-I-FRAMES-ONLY',
  extXByterange: '#EXT-X-BYTERANGE',
  extXIframeStreamInf: '#EXT-X-I-FRAME-STREAM-INF',
  extXDiscontinuity: '#EXT-X-DISCONTINUITY',
  extXCueOutStart: '#EXT-X-CUE-OUT',
  extXCueOut: '#EXT-X-CUE-OUT-CONT',
  extIsIndependentSegments: '#EXT-X-INDEPENDENT-SEGMENTS',
  extXScte35: '#EXT-OATCLS-SCTE35',
  extXCueStart: '#EXT-X-CUE-OUT',
  extXCueEnd: '#EXT-X-CUE-IN',
  extXCueSpan: '#EXT-X-CUE-SPAN',
  extXMap: '#EXT-X-MAP',
  extXStart: '#EXT-X-START',
};
