name: Release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          check-latest: true

      - name: Install dependencies
        run: npm ci

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: 'v${{ env.PACKAGE_VERSION }}'
          generate_release_notes: true

permissions:
  contents: write
